// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package manage_service

import (
	"database/sql"
	"time"
)

type ManageService struct {
	ID           string
	Name         sql.NullString
	Code         string
	Prefix       sql.NullString
	NumberStarts sql.NullInt32
	NumberEnds   sql.NullInt32
	Hide         sql.NullBool
	ShowDisplay  sql.NullBool
	Description  sql.NullString
	StartTime    sql.NullTime
	EndTime      sql.NullTime
	DefaultTime  sql.NullInt32
	Workflow     sql.NullString
	BranchCode   string
	BranchName   sql.NullString
	CompanyCode  string
	CompanyName  sql.NullString
	UpdatedAt    time.Time
	CreatedAt    time.Time
	UpdatedBy    sql.NullString
}
