// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package branch_admin

import (
	"database/sql"
	"time"
)

type BranchAdmin struct {
	ID          string
	BranchName  sql.NullString
	BranchCode  string
	CompanyCode string
	CompanyName sql.NullString
	Username    sql.NullString
	Firstname   sql.NullString
	Lastname    sql.NullString
	Email       sql.NullString
	CreatedAt   time.Time
	CreatedBy   sql.NullString
	UpdatedAt   time.Time
	UpdatedBy   sql.NullString
}
