// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package manage_section

import (
	"database/sql"
	"time"
)

type ManageSection struct {
	ID           string
	Name         sql.NullString
	BenchWait    sql.NullInt32
	BenchProcess sql.NullInt32
	Description  sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CreatedBy    sql.NullString
	UpdatedBy    sql.NullString
	CompanyCode  string
	BranchCode   string
	CompanyName  sql.NullString
	BrachName    sql.NullString
}
