// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package manage_counter

import (
	"database/sql"
	"time"
)

type ManageCounter struct {
	ID               string
	Section          sql.NullString
	SubSection       sql.NullString
	UserID           string
	CounterNumber    sql.NullString
	CounterName      sql.NullString
	OverrideFifo     sql.NullBool
	TransferQ        sql.NullBool
	AsssignUser      sql.NullBool
	AssignService    sql.NullBool
	TransferPriority sql.NullBool
	CancelQ          sql.NullBool
	TransferFinish   sql.NullBool
	MergeSection     sql.NullBool
	EndQ             sql.NullBool
	BranchCode       string
	BranchName       sql.NullString
	CompanyName      sql.NullString
	CompanyCode      string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CreatedBy        sql.NullString
	UpdatedBy        sql.NullString
}
