// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package manage_users

import (
	"database/sql"
	"time"
)

type ManageUser struct {
	ID          string
	Email       string
	Firstname   sql.NullString
	Lastname    sql.NullString
	CreatedAt   time.Time
	UserType    sql.NullString
	Suspended   sql.NullBool
	BranchName  sql.NullString
	BranchCode  string
	CompanyName sql.NullString
	CompanyCode string
	Title       sql.NullString
	Password    sql.NullString
	ImageUrl    sql.NullString
	UpdatedAt   time.Time
	CreatedBy   sql.NullString
	UpdatedBy   sql.NullString
}
