// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package manage_branch

import (
	"database/sql"
	"time"
)

type ManageBranch struct {
	ID             string
	Code           string
	Name           sql.NullString
	License        sql.NullString
	Services       sql.NullString
	Address        sql.NullString
	Phone          sql.NullString
	LicenseKey     sql.NullString
	CheckInUrl     sql.NullString
	TicketPageUrl  sql.NullString
	DisplayUrl     sql.NullString
	CompanyCode    string
	CreatedAt      time.Time
	CreatedBy      sql.NullString
	UpdatedAt      time.Time
	UpdatedBy      sql.NullString
	PrinterDetails sql.NullString
}
