CREATE TABLE `manage_counters` (
  `id` varchar(255) NOT NULL,
  `section` varchar(255) DEFAULT NULL,
  `sub_section` varchar(255) DEFAULT NULL,
  `user_id` varchar(255) NOT NULL,
  `counter_number` varchar(255) DEFAULT NULL,
  `counter_name` varchar(255) DEFAULT NULL,
  `override_fifo` tinyint(1) DEFAULT NULL,
  `transfer_q` tinyint(1) DEFAULT NULL,
  `asssign_user` tinyint(1) DEFAULT NULL,
  `assign_service` tinyint(1) DEFAULT NULL,
  `transfer_priority` tinyint(1) DEFAULT NULL,
  `cancel_q` tinyint(1) DEFAULT NULL,
  `transfer_finish` tinyint(1) DEFAULT NULL,
  `merge_section` tinyint(1) DEFAULT NULL,
  `end_q` tinyint(1) DEFAULT NULL,
  `branch_code` varchar(255) NOT NULL,
  `branch_name` varchar(255) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `company_code` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` varchar(255) DEFAULT NULL,
  `updated_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`,`user_id`,`branch_code`,`company_code`)
)