// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package ticket

import (
	"database/sql"
)

type Ticket struct {
	ID               string
	Service          sql.NullString
	TicketStatus     sql.NullBool
	CounterID        sql.NullString
	TransferedTo     sql.NullString
	TransferedBy     sql.NullString
	CustomerID       sql.NullString
	TicketNumber     sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	UpdatedBy        sql.NullString
	StartedServingAt sql.NullTime
	EndServingAt     sql.NullTime
	TicketName       sql.NullString
	CompanyName      sql.NullString
	CompanyCode      string
	BranchCode       string
	BranchName       sql.NullString
}
